---
title: Powershell and Calling External Executables
layout: post
---

<p>In my last post on <a href="http://www.headspring.com/2011/08/avoiding-on-error-resume-next-when-using-powershell">error handling when using Powershell</a>, we saw how Powershell's default behavior for uncaught exceptions allows the rest of your script to continue running in a likely-invalid state, and how setting <strong>$global:ErrorActionPreference = "Stop"</strong> changes that behavior to stop as soon as an uncaught exception surfaces.</p>
<p>Unfortunately, we can <em>still</em> be surprised by Powershell's error handling behavior. There are two main categories of errors your Powershell script might encounter:</p>
<ol>
<li>Uncaught exceptions thrown by your Powershell process.</li>
<li>Failure exit codes returned by external programs that your Powershell process invoked.<!--more--></li>
</ol>
<p>When we set the ErrorActionPreference to "Stop", we only change the behavior of uncaught exceptions. We have to work a little harder to cover the other category. Consider a Powershell script that calls out to an external program which returns its own failure exit code:</p>
<p>{% gist 1150145 %}</p>
<p>External executables are invoked using similar syntax as Powershell commands like <code>write-host</code>, so it isn't obvious that there's anything special about the call to <code>schtasks</code>. Since it is an external program, however, it can't exactly throw a .NET exception - it might not even <em>be</em> a .NET program.</p>
<p>The lingua franca of command-line failure is exit codes, rather than exceptions. An exit code of 0 means "all is well", and anything else should be treated as a failure.</p>
<p>We have two problems:</p>
<ol>
<li>calls to external programs don't feel special to the reader, even though they behave differently from normal Powershell commands</li>
<li>we're tempted to explicitly follow each external call with a corresponding test-and-throw code block, which would be ugly and distracting to the reader</li>
</ol>
<p>Fortunately, we can take advantage of Powershell's flexible syntax to address both of these concerns. It turns out that a Powershell function can accept a <em>code block</em> as an argument, effectively allowing us to add new keywords to the language. Consider the helper function 'exec':</p>
<p>{% gist 1150147 %}</p>
<p>When we use exec, we can pass it a { code block surrounded in braces }. This way we can make our external commands stand out as special, using just one new 'keyword', and we get the error handling we wanted to boot:</p>
<p>{% gist 1150152 %}</p>
<p>Eureka! We can ensure that both categories of failures will stop execution dead in its tracks.</p>
<p>To sum up, the default error handling behavior in Powershell is dramatically different from that of other .NET languages. <strong>By default, your script will happily and disasterously continue running even when throwing exceptions.</strong> This can leave the user of the script confused as to whether the process has actually succeeded or failed. By setting the global ErrorActionPreference and by wrapping external commands with the 'exec' helper function, Powershell's behavior can become what we expected in the first place.</p>
